import ReportChartCard from './ReportChartCard';
import ReportTable from './ReportTable';
import { formatReportDateLabel, formatReportDateRange } from '../../lib/date';

function hasChartData(chart) {
    return Array.isArray(chart?.labels)
        && chart.labels.length > 0
        && Array.isArray(chart?.datasets)
        && chart.datasets.some(dataset => Array.isArray(dataset.data) && dataset.data.some(value => Number(value) > 0));
}

function formatTotalValue(value) {
    if (value === null || value === undefined || value === '') {
        return 'N/A';
    }

    if (typeof value === 'object') {
        return JSON.stringify(value);
    }

    return String(value);
}

export default function ReportPreview({ report }) {
    if (!report) {
        return (
            <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-8 text-center">
                <p className="text-sm font-semibold text-slate-500">Preview a report to see the printable output.</p>
            </div>
        );
    }

    const totals = Object.entries(report.totals || {});
    const missingData = Array.isArray(report.missing_data) ? report.missing_data.filter(Boolean) : [];
    const dateRangeLabel = formatReportDateRange(report.date_range?.start_date, report.date_range?.end_date, {
        fallback: report.date_range?.label || 'N/A'
    });
    const generatedAtLabel = formatReportDateLabel(report.generated_at, { fallback: report.generated_at || 'N/A' });

    return (
        <section className="report-print-area space-y-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm print:border-0 print:p-0 print:shadow-none">
            <header className="border-b border-slate-200 pb-5">
                <p className="text-sm font-black uppercase tracking-[0.2em] text-[#155dfc]">iPawcus</p>
                <h1 className="mt-1 text-2xl font-black text-slate-950">Vetfocus Care Animal Clinic</h1>
                <div className="mt-4 grid gap-2 text-sm font-semibold text-slate-600 sm:grid-cols-2">
                    <p><span className="text-slate-950">Report:</span> {report.title}</p>
                    <p><span className="text-slate-950">Date Range:</span> {dateRangeLabel}</p>
                    <p><span className="text-slate-950">Generated:</span> {generatedAtLabel}</p>
                    <p><span className="text-slate-950">Generated By:</span> {report.generated_by || 'Super Admin'}</p>
                </div>
            </header>

            <div className="space-y-3">
                <h2 className="text-lg font-black text-slate-950">Summary</h2>
                <p className="text-sm font-semibold leading-6 text-slate-600">{report.summary?.text || 'No summary available.'}</p>
                {Array.isArray(report.summary?.bullets) && report.summary.bullets.length ? (
                    <ul className="grid gap-2 text-sm font-semibold text-slate-600 sm:grid-cols-2">
                        {report.summary.bullets.map((line, index) => (
                            <li key={`${line}-${index}`} className="rounded-lg bg-slate-50 px-3 py-2 print:border print:border-slate-200 print:bg-white">
                                {line}
                            </li>
                        ))}
                    </ul>
                ) : null}
            </div>

            {totals.length ? (
                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                    {totals.slice(0, 8).map(([key, value]) => (
                        <div key={key} className="rounded-lg border border-slate-200 p-3">
                            <p className="text-[11px] font-black uppercase tracking-wide text-slate-500">{key.replaceAll('_', ' ')}</p>
                            <p className="mt-1 break-words text-sm font-black text-slate-950">{formatTotalValue(value)}</p>
                        </div>
                    ))}
                </div>
            ) : null}

            {missingData.length ? (
                <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm font-semibold leading-6 text-amber-900">
                    {missingData.map((note, index) => (
                        <p key={`${note}-${index}`}>{note}</p>
                    ))}
                </div>
            ) : null}

            {hasChartData(report.chart) ? (
                <div className="report-print-hidden">
                    <ReportChartCard title={`${report.title} Chart Preview`} summary="" chart={report.chart} compact />
                </div>
            ) : null}

            <div className="space-y-3">
                <h2 className="text-lg font-black text-slate-950">Detailed Records</h2>
                <ReportTable columns={report.columns} rows={report.rows} />
            </div>

            <footer className="border-t border-slate-200 pt-4 text-xs font-semibold text-slate-500">
                Generated by iPawcus: A Web-Based Veterinary Management System
            </footer>
        </section>
    );
}
